# train configuration

exp_dir: 'exp'
mode: 'clean'

# Data Loader
batch_size: 256
num_workers: 6
min_frames: 200
max_frames: 201
eval_frames: 0
sample_rate: 16000
aug_prob: 0.8

# Training details
max_epochs: 40
nnet_type: 'ResNet34'
pooling_type: 'ASP'


# Testing details
eval_interval: 1
eval_size: 5000

# Optimizer
learning_rate: 0.0001
lr_step_size: 1
lr_gamma: 0.95
auto_lr: False

# Training and test data
train_list: 'The path of training data list'
train_path: 'The directory of training data'
musan_path: 'The directory of MUSAN data'
rir_path: 'The directory of RIR data'
test_path: 'The directory of evaluation data'
trials_path: 'The path of evaluation trial list'

# Load and save
pretrain: './source/resnet34_avg.ckpt'
checkpoint_path: null
save_top_k: -1
save_path: 'resnet34_transformer_clean'
hardspk_path: 'The path of hard speaker sampling dict'

# Model definition
n_mels: 80
embedding_dim: 256
hidden_dim: 256
d_ff: 512
num_heads: 4
num_layers: 8
max_len: 500

# Test mode
evaluate: False